### ISSUE TITLE
Does not seem to work 

### ISSUE THREAD

**Issue by Natey214** [bdew/jeibees#1]
I am using Forestry 5.2.17.360.jar, JEI 3.14.3.403, and Forge 12.18.3.2185 and when pressing the recipe or uses button on any drone, princess, or queen, nothing comes up.

**Comment by bdew** [comment]
Please post your client log.

I tried the exact combination of versions and it works for me, might be something caused by another mod.

At any rate, the logs should shed more light on what's going wrong.
