### ISSUE TITLE
[1.12.2] drop the client-side requirement

### ISSUE THREAD

**Issue by SoniEx2** [bdew/jeibees#11]
Running JEI Bees on a server forces clients to have it installed. While it makes sense to sync mod content, it should still not require the client to have the mod (and thus all of JEI, which is a massive RAM hog due to all the recipe indexing and whatnot) installed.

**Comment by bdew** [comment]
The mod doesn't do anything useful on a server so you can just not install it server-side.
At any rate as of 1.16 it should be optional on either side. Earlier versions will not be updated.
