### ISSUE TITLE
Jei Bees don't show recipe when i try to look at them

### ISSUE THREAD

**Issue by POKFX45** [bdew/jeibees#2]
I am using the latest version of Forestry (5.2.17.362) and Jei(3.14.4.404) for MC 1.10.2 when i try to look at the recipe nothing shows up, here it is the log:
http://paste.ee/p/sMQOD
( I really don't know where the problem is, I'm sorry I can't help you more)

**Comment by bdew** [comment]
You have dozens of errors from JEI, JER, Forestry, etc.

I suspect something in your setup is borked. Check that all your mods are of the right version, no corrupted JARs, etc.
