### ISSUE TITLE
Issues with Recipes

### ISSUE THREAD

**Issue by yepidoodles** [bdew/jeibees#4]
Hello there,

Some of my players are reporting that their bees/ trees recipes aren't showing (Others say they work fine). One has said that just one isn't showing, Leporine. 

Forestry: 5.2.17.376
More Bees: 1.3.2
JEI: 3.14.7.419
JEI Bees: 0.9.0.5
Forge: 2297
SpongeForge: 2281-5.2.0-BETA-2353
Modpack: https://www.technicpack.net/modpack/elbeta.705651

If you need anything else to investigate this issue, please ask.

- Alice Sellars
[DragonTechMC](http://dragontechmc.com)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
