### ISSUE TITLE
JEI Bees Plugins fails to load

### ISSUE THREAD

**Issue by TeknoKit** [bdew/jeibees#5]
I have made a small personal mod to learn Minecraft modding and added various bees to Forestry.
However when I try to use your plugin with the build or in a modded game, JEI Bees fails to load due to a NullPointerException thrown by a Forestry method called from the plugin. This only happens when my mod is loaded; but my mod is not in the stack-trace and itself throws no errors and works perfectly fine with Forestry within the game after much testing.

[https://pastebin.com/CtNiQ41Z](url)

**Comment by bdew** [comment]
From the look of things the template for your species is either not registered at all or has null chromosomes in it.

Is your mod available anywhere so i can look at it?

**Comment by TeknoKit** [comment]
Here it is: https://github.com/TeknoKit/foxbees/tree/1.11.2

**Comment by TeknoKit** [comment]
Well it took quite a while but I figured out the problem. I had figured it might have been on me but I just could not solve it till now. I was attempting to call an OreDic item before another mod registered that item.
Nothing wrong with your end.
