### ISSUE TITLE
[1.12.2] JEI Bees always shows secret bees

### ISSUE THREAD

**Issue by kekvitirae** [bdew/jeibees#8]
Even when the config setting 
    B:ShowSecret=false
JEI Bees will still show secret bees.

https://i.imgur.com/qBreV9D.png

Forestry: 5.8.0.256
Gendustry: 1.6.5.8
JEI Bees: 0.9.0.5
Magic Bees: 3.1.9

**Comment by bdew** [comment]
This setting only applies to secret mutations (marked as such in the API), i clarified it in the config file for 1.16.
