### ISSUE TITLE
Support for bees with more than 3 products.

### ISSUE THREAD

**Issue by Hazmatik** [bdew/jeibees#9]
Some bees produce more than 3 different things and JEI Bees only shows the first 3 products with percentages.
For example I searched the recipe for glowstone dust and it tells me Devil and Assassin bees (career bees mod) produce it but I don't actually see it under their entry with the percentage for the chance they have to produce it.
[![Image from Gyazo](https://i.gyazo.com/690ec9f049e3614e2883895aa009bd92.png)](https://gyazo.com/690ec9f049e3614e2883895aa009bd92)

**Comment by bdew** [comment]
Fixed in 1.16 port, earlier versions won't be updated.
